### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [cbmarc/EAN128-4php#1]
Not working at all. Tested with

&lt;img src="EAN128-4php/EAN128-4php.php?barcode=991234456123456789005001"/&gt;

Calling directly the script and modifying the barcode_outputfile function (around line 50), I get the output barcode image:

...
        header('Content-Type: image/png');
    imagepng($image, null);
    exit;
...

**Comment by cbmarc** [comment]
Hi, thanks for reporting. I'll have a look at it later. Keep in touch.

**Comment by cbmarc** [comment]
Should work now. If it doesn't, please reopen another issue and provide more info about php config.
